#ifndef __DialogVorhandenenEintragOeffnen__
#define __DialogVorhandenenEintragOeffnen__

/**
@file
Subclass of DialogVorhandenenEintragOeffnenBase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"

//// end generated include

/** Implementing DialogVorhandenenEintragOeffnenBase */
class DialogVorhandenenEintragOeffnen : public DialogVorhandenenEintragOeffnenBase
{
	protected:
		// Handlers for DialogVorhandenenEintragOeffnenBase events.
		void OnButtonJaVorhandenenBerichtOeffnen( wxCommandEvent& event );
		void OnButtonNeinVorhandenenBErichtNichtOeffnen( wxCommandEvent& event );
	public:
		/** Constructor */
		DialogVorhandenenEintragOeffnen( wxWindow* parent );
	//// end generated class members

};

#endif // __DialogVorhandenenEintragOeffnen__
