#ifndef __DialogNameAnlegen__
#define __DialogNameAnlegen__

/**
@file
Subclass of DialogNameAnlegenbase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"

//// end generated include

/** Implementing DialogNameAnlegenbase */
class DialogNameAnlegen : public DialogNameAnlegenbase
{
	protected:
		// Handlers for DialogNameAnlegenbase events.
		void OnOKClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		DialogNameAnlegen( wxWindow* parent );
	//// end generated class members

};

#endif // __DialogNameAnlegen__
