#ifndef __FrameBerichtshefteintrag__
#define __FrameBerichtshefteintrag__

/**
@file
Subclass of FrameBerichtshefteintragbase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"
#include "../../mk_sqlite/database.h"


//// end generated include


wxDECLARE_EVENT(FrameBerichtshefteintrag_Updated, wxCommandEvent);

/** Implementing FrameBerichtshefteintragbase */
class FrameBerichtshefteintrag : public FrameBerichtshefteintragbase
{
   mk::sqlite::database _db;

   void ResetNameChoice();
   void ResetAbteilungChoice();
   void OnButtonNeuName(wxCommandEvent& event)override;
   void OnButtonNeuAbteilung( wxCommandEvent& event )override;
   void OnCalendarVonChanged(wxCalendarEvent& event)override;
   void OnCalendarBisChanged(wxCalendarEvent& event)override;
   void OnButtonSpeichern(wxCommandEvent& event)override;
   void OnButtonDrucken( wxCommandEvent& event )override { event.Skip(); }

	public:
		/** Constructor */

		void panelbetriebstaetigkeiterstellen();
		void panelschultaetigkeiterstellen();

		FrameBerichtshefteintrag( wxWindow* parent, mk::sqlite::database db);
	//// end generated class members

};

#endif // __FrameBerichtshefteintrag__






