#ifndef __FrameBerichtshefteintrag__
#define __FrameBerichtshefteintrag__

/**
@file
Subclass of FrameBerichtshefteintragbase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"
#include "../../mk_sqlite/database.h"
#include "wx/log.h"


//// end generated include


wxDECLARE_EVENT(FrameBerichtshefteintrag_Updated, wxCommandEvent);

/** Implementing FrameBerichtshefteintragbase */
class FrameBerichtshefteintrag : public FrameBerichtshefteintragbase
{
   mk::sqlite::database _db;

   void ResetNameChoice();
   void ResetAbteilungChoice();
   void OnButtonNeuName(wxCommandEvent& event)override;
   void OnButtonNeuAbteilung( wxCommandEvent& event )override;
   void OnCalendarVonChanged(wxCalendarEvent& event)override;
   void OnCalendarBisChanged(wxCalendarEvent& event)override;
   void OnButtonSpeichern(wxCommandEvent& event)override;
   void OnButtonDrucken( wxCommandEvent& event )override { event.Skip(); }

	public:
		/** Constructor */

		void panelbetriebstaetigkeiterstellen();
		void panelschultaetigkeiterstellen();

		FrameBerichtshefteintrag( wxWindow* parent, mk::sqlite::database db);
	//// end generated class members

		virtual void OnBetriebTaetigkeitErstellen(wxCommandEvent& event) 
		{
			auto _paneltaetigkeitbetriebneu = new PanelTaetigkeitbase(_panelBetrieb/*_panelSchule*/);
			_betriebtaetigkeitsizer->Add(_paneltaetigkeitbetriebneu);
			bSizer7->Layout();
			bSizer1->Layout();


			//_betriebtaetigkeitsizer->Layout();
			//_schultaetigkeitsizer->Layout();
			//wxLogMessage("Hallo test BetriebErstellen");
		}

		virtual void OnBetriebTaetigkeitLoeschen(wxCommandEvent& event) 
		{
			//wxLogMessage("Hallo test BetriebLoeschen");

			//auto count = _betriebtaetigkeitsizer->GetItemCount();
			_betriebtaetigkeitsizer->Detach(0);
			_betriebtaetigkeitsizer->Layout();
			//bSizer7->Layout();
			bSizer1->Layout();

		}


		virtual void OnSchuleTaetigkeitErstellen(wxCommandEvent& event) 
		{
			//wxLogMessage("Hallo test SchuleErstellen");
			auto _paneltaetigkeitschuleneu = new PanelTaetigkeitbase(_panelSchule);
			_schultaetigkeitsizer->Add(_paneltaetigkeitschuleneu);
			bSizer7->Layout();
			bSizer1->Layout();	
		}


		virtual void OnSchuleTaetigkeitLoeschen(wxCommandEvent& event) 
		{
			//wxLogMessage("Hallo test schuleLoeschen");

			_schultaetigkeitsizer->Detach(0);

			_schultaetigkeitsizer->Layout();
			//bSizer7->Layout();
			bSizer1->Layout();
		}

};

#endif // __FrameBerichtshefteintrag__

