#ifndef __Mainframe__
#define __Mainframe__

/**
@file
Subclass of Mainframebase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"
#include "../../mk_sqlite/database.h"

//// end generated include

/** Implementing Mainframebase */
class Mainframe : public Mainframebase
{
   std::unique_ptr<mk::sqlite::database> _db;

   void NeueDatenbank () ;

	public:
		/** Constructor */
		Mainframe( wxWindow* parent );


	//// end generated class members

};

#endif // __Mainframe__
