#ifndef __Mainframe__
#define __Mainframe__

/**
@file
Subclass of Mainframebase, which is generated by wxFormBuilder.
*/

#include "Berichtsheft.h"

//// end generated include

/** Implementing Mainframebase */
class Mainframe : public Mainframebase
{
	public:
		/** Constructor */
		Mainframe( wxWindow* parent );
	//// end generated class members

};

#endif // __Mainframe__
